### ISSUE TITLE
Exclude Folders  option (/xd) should not append the source directory

### ISSUE THREAD

**Issue by adnan-kamili** [mikeobrien/node-robocopy#1]
The /xd option in robocopy just takes the folder name and the same folder is excluded even if it is present in some sub-directory.

But, in command.js the the source directory is appended to the xd dirs which makes it exclude directories at only level one.

```
       if (file.excludeDirs && file.excludeDirs.length > 0) {
        args.push('/xd');

           /*      Not needed     
            var excludeDirs = 
            _.chain(toAbsolutePath(file.excludeDirs, source)
                .concat(toAbsolutePath(file.excludeDirs, "")))
                .uniq()
                .map(toWindowsPath)
                .map(qualify)
                .value();*/
        /* It should simply be */
        args = args.concat(qualify(toWindowsPath(file.excludeDirs)));
    }
```

**Comment by mikeobrien** [comment]
This is actually in there to support absolute path exclusions for mirroring. If you want to submit a PR to add the the functionality you proposed that would be great as that is a common use case. We'd basically need to add a flag along the lines of `{ file: { excludeDirsAbsolute: true|false } }` that defaults to true (To support backwards compatibility). And it would toggle the existing behavior and the one you propose.
