### ISSUE TITLE
I am not able to connect to remote server with gulp this one 

### ISSUE THREAD

**Issue by vinzandtonz** [mikeobrien/node-robocopy#3]
I am not able to connect to remote server with gulp this one  

var robocopy = require('robocopy');

gulp.task('robo', function() {
    return robocopy({
        source: 'build',
        destination: '\\domainname\d$\testing\build',
        files: ['_._'],
        copy: {
            mirror: true
        },
        file: {
            excludeFiles: ['packages.config'],
            excludeDirs: ['obj', 'Properties'],
        },
        retry: {
            count: 2,
            wait: 3
        }
    });
});

**Comment by mikeobrien** [comment]
You'll need to provide more information if you want help.

**Comment by 1-0-1** [comment]
+1
It looks like the one I just posted is a duplicate of this.  Network paths are getting converted to local paths.
