### ISSUE TITLE
Path Fails on Network Path

### ISSUE THREAD

**Issue by 1-0-1** [mikeobrien/node-robocopy#4]
I'm not able to use a network path ("\\servername\share$\location\directory").
It is converting it to a local path: "C:\servernameshare$locationdirectory\"

**Comment by mikeobrien** [comment]
Thx for reporting this! I'm super swamed ATM so don't know when I'll be able to look at it. If you're interested in digging in and doing a PR that would be awesome!

**Comment by 1-0-1** [comment]
If I escape the path name back slashes, it works.
"\\\\servername\\share$\\location\\directory"

However it never returns.  I just sits there until ctrl+c breaks it out.

**Comment by 1-0-1** [comment]
Just takes awhile to return.  This can be closed possibly with a comment about escaping back slashes in network paths.

**Comment by mikeobrien** [comment]
Ahhh, yeah, makes sense.
