### ISSUE TITLE
ACCESS Denied error while trying to access remote server

### ISSUE THREAD

**Issue by francisminu** [mikeobrien/node-robocopy#6]
Hi,

I am trying to create a gulp task to deploy my Angular application to a remote Windows Server. I am using Robocopy to copy the files from my local to the remote server. I have given the below destination, but it comes back with the below error:

ERROR 5 (0x00000005) Creating Destination Directory \\servername\E$\testresults \user:myusername mypassword\
Access is denied.

Please find below the code that I have for copying from source to destination:

gulp.task('deploy', function() {
    return robocopy({
        source: './test/',
        destination: '//servername//E$//testresults /user:domain/myusername mypassword',
        files: ['*.config', '*.html', '*.htm', '*.js', '*.dll', '*.pdb','*.txt',
                '*.png', '*.jpg', '*.jpeg', '*.gif', '*.css'],
    });
});

Please advise on what is going wrong.
I have checked the permissions on the drive and there is full control for everyone on the E drive on this server.

**Comment by mikeobrien** [comment]
It could be the permissions on the share then. Either way, this doesn't have anything to do with the lib.
